spring:
  application:
    name: tes-service
  cloud:
    kubernetes:
      discovery:
        enabled: false
      ribbon:
        enabled: false
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411

foo-service:
  ribbon:
    listOfServers: localhost:9999
bar-service:
  ribbon:
    listOfServers: localhost:9999
